name: location_web
description: The web implementation of the location plugin.
version: 2.0.0
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  js: ^0.6.3
  location_platform_interface:
    path: ../location_platform_interface
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: LocationWebPlugin
        fileName: location_web.dart
