name: location
description: A Flutter plugin to easily handle realtime location in iOS and Android. Provides settings for optimizing performance or battery.
version: 4.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

flutter:
  plugin:
    platforms:
      android:
        package: com.lyokone.location
        pluginClass: LocationPlugin
      ios:
        pluginClass: LocationPlugin
      macos:
        pluginClass: LocationPlugin
      web:
        default_package: location_web

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface: 
    git:
        url: https://github.com/hartkern82/flutter_location.git
        path: "location_platform_interface"
        ref: 2.0.0
  location_web: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.5
